--liquibase formatted sql

--changeset osipov:001-users
CREATE TABLE users (
                       id          NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name        VARCHAR2(255)   NOT NULL,
                       email       VARCHAR2(320)   NOT NULL,
                       created_at  TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
                       CONSTRAINT uk_users_email UNIQUE (email)
);

--rollback DROP TABLE users;