--liquibase formatted sql

--changeset osipov:002-products
CREATE TABLE products (
                          id          NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          name        VARCHAR2(255)   NOT NULL,
                          price       NUMBER(18,2)    NOT NULL,
                          stock       NUMBER(10)      DEFAULT 0 NOT NULL,
                          status      VARCHAR2(20)    DEFAULT 'ACTIVE' NOT NULL,
                          created_at  TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
                          updated_at  TIMESTAMP(6),
                          CONSTRAINT chk_products_status CHECK (status IN ('ACTIVE','INACTIVE'))
);

--changeset osipov:002-products-indexes
CREATE INDEX idx_products_status ON products(status);

--rollback DROP INDEX idx_products_status; DROP TABLE products;