--liquibase formatted sql

--changeset osipov:003-orders
CREATE TABLE orders (
                        id             NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        user_id        NUMBER(19)     NOT NULL,
                        status         VARCHAR2(20)   DEFAULT 'NEW' NOT NULL,
                        created_at     TIMESTAMP(6)   DEFAULT SYSTIMESTAMP NOT NULL,
                        updated_at     TIMESTAMP(6),
                        CONSTRAINT fk_orders_user     FOREIGN KEY (user_id) REFERENCES users(id),
                        CONSTRAINT chk_orders_status  CHECK (status IN ('NEW','PAID','CANCELLED','COMPLETED'))
);

--changeset osipov:003-orders-indexes
CREATE INDEX idx_orders_user   ON orders(user_id);
CREATE INDEX idx_orders_status ON orders(status);
CREATE INDEX idx_orders_created_at ON orders(created_at);

--rollback DROP INDEX idx_orders_created_at; DROP INDEX idx_orders_status; DROP INDEX idx_orders_user; DROP TABLE orders;
