--liquibase formatted sql

--changeset you:005-payments
CREATE TABLE payments (
                          id           NUMBER(19) GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          order_id     NUMBER(19)   NOT NULL,
                          amount       NUMBER(18,2) NOT NULL,
                          status       VARCHAR2(20) DEFAULT 'PENDING' NOT NULL,
                          payment_date TIMESTAMP(6),
                          provider     VARCHAR2(64),
                          external_id  VARCHAR2(128),
                          CONSTRAINT fk_pay_order       FOREIGN KEY (order_id) REFERENCES orders(id),
                          CONSTRAINT uk_pay_external_id UNIQUE (external_id),
                          CONSTRAINT chk_pay_status     CHECK (status IN ('PENDING','COMPLETED','FAILED'))
);

--changeset you:005-payments-indexes
CREATE INDEX idx_pay_order   ON payments(order_id);
CREATE INDEX idx_pay_status  ON payments(status);

--rollback DROP INDEX idx_pay_status; DROP INDEX idx_pay_order; DROP TABLE payments;
